server:
  port: 10008
  servlet:
    context-path: /abuseipdb-service/v1

info:
  app:
    name: abuseipdb-Service
    description: ASH Technology Solutions AbuseIPDB Service
    version: 1.0.0

spring:
  application:
    name: abuseipdb-Service
  config:
    activate:
      on-profile: ionos4

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

abuse:
  ip:
    db:
      key: ENC(iI6bG3uf1kG0HScUmpK+dmAZz5crig8j7aVZQh6eIHszKw/clk4nDn2EnMv/V+A+Sco7X81sJz44pD8KRVOOeUsYITJu5nl+LIC+4aWmuOAlMth1ntPjVWkE+dTiHPbZ)
      check.ip.url: https://api.abuseipdb.com/api/v2/check
      report.ip.url: https://api.abuseipdb.com/api/v2/report
      report.bulk.ip.url: https://api.abuseipdb.com/api/v2/bulk-report
      max.age.in.days: 90

logging:
  pattern:
    console: "[%d] [%t] [%L] %-5level %logger : %msg%n"
  level:
    root: info
    com.tech.ash.abuseipdb: info

---
server:
  port: 10008
  servlet:
    context-path: /abuseipdb-service/v1

spring:
  config:
    activate:
      on-profile: default

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

abuse:
  ip:
    db:
      key: ENC(iI6bG3uf1kG0HScUmpK+dmAZz5crig8j7aVZQh6eIHszKw/clk4nDn2EnMv/V+A+Sco7X81sJz44pD8KRVOOeUsYITJu5nl+LIC+4aWmuOAlMth1ntPjVWkE+dTiHPbZ)
      check.ip.url: https://api.abuseipdb.com/api/v2/check
      report.ip.url: https://api.abuseipdb.com/api/v2/report
      report.bulk.ip.url: https://api.abuseipdb.com/api/v2/bulk-report
      max.age.in.days: 90

logging:
  pattern:
    console: "[%d] [%t] [%L] %-5level %logger : %msg%n"
  level:
    root: info
    com.tech.ash.abuseipdb: debug

